### PR TITLE
Create `Html_Forms.md`

### PR DESCRIPTION
**Pull request by iatharva**
As mentioned in #1

## What is the change?
Added `Html_Forms.md` with information about it. 

## Related issue?
closes: #1 

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

-   [x] I have followed the [Code of Conduct](https://github.com/HackClubRAIT/Wizard-Of-Docs/blob/ec224497bce316f7b4736a901f70688f251cca87/CODE_OF_CONDUCT.md).
-   [x] I have checked there aren't other open [Pull Requests](https://github.com/HackClubRAIT/Frontend-Owls/pulls) for the same update/change.
-   [x] I have you tested the code before submission.
-   [x] I have commented my code, particularly in hard-to-understand areas.
-   [x] My changes generates no new warnings.
-   [x] I'm Hacktoberfest'21 contributor.

### CODE REVIEW

**Comment by siddhi-244** [comment]
you haven't added any info about the forms !!!

**Comment by siddhi-244** [comment]
> In the description of the issue, it was given that the task/issue was to `Add a file Html_Forms.md in html folder`. Was there anything else that I needed to do?

You have to explain about Html forms. It's a documentation repo

**Comment by iatharva** [comment]
Oh sorry my bad, now I got it! will update the file asap.

**Comment by iatharva** [comment]
I have added the information. Please do review it.

**Review by siddhi-244 — CHANGES_REQUESTED** [review]
It would be really great if you can add about input types.

**Comment by iatharva** [comment]
> It would be really great if you can add about input types.

Should I add it in detail, would that be fine?

**Comment by siddhi-244** [comment]
> > It would be really great if you can add about input types.
> 
> Should I add it in detail, would that be fine?

Yes. You are going great🎊🎊🎊

**Review by siddhi-244 — APPROVED** [review]
Great work🎊🎊

**Comment by iatharva** [comment]
Thanks, do let me know if you have any more issues/tasks.

**Review by girija0707 — APPROVED** [review]
LGTM, good job

**Comment by siddhi-244** [comment]
> Thanks, do let me know if you have any more issues/tasks.

You can create new issues

**Pull request merged**
