### PR TITLE
create CSS Box_Model.md

### PR DESCRIPTION
**Pull request by dickyrex19**
## What is the change?
Added CSS_Box_Model.md and modify the contents

## Related issue?
closes: #11 

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

-   [x] I have followed the [Code of Conduct](https://github.com/HackClubRAIT/Wizard-Of-Docs/blob/ec224497bce316f7b4736a901f70688f251cca87/CODE_OF_CONDUCT.md).
-   [x] I have  checked there aren't other open [Pull Requests](https://github.com/HackClubRAIT/Frontend-Owls/pulls) for the same update/change.
-   [ ] I have you tested the code before submission.
-   [ ] I have commented my code, particularly in hard-to-understand areas.
-   [x] My changes generates no new warnings.
-   [x] I'm Hacktoberfest'21 contributor.

### CODE REVIEW

**Comment by siddhi-244** [comment]
It's plagiarized.  Please try to write documentation by your own.

**Comment by dickyrex19** [comment]
here the new documentation can you please review this one

**Review by girija0707 — APPROVED** [review]
you really did a wonderful job ,keep up the good work

**Review by siddhi-244 — APPROVED** [review]
LGTM

**Pull request merged**
