### PR TITLE
carousel_document

### PR DESCRIPTION
**Pull request by Koustavjr**
## What is the change?
Remove this line and add a description

## Related issue?
closes: #issue_number

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

-   [x ] I have followed the [Code of Conduct](https://github.com/HackClubRAIT/Wizard-Of-Docs/blob/ec224497bce316f7b4736a901f70688f251cca87/CODE_OF_CONDUCT.md).
-   [ x] I have  checked there aren't other open [Pull Requests](https://github.com/HackClubRAIT/Frontend-Owls/pulls) for the same update/change.
-   [ x] I have you tested the code before submission.
-   [ x] I have commented my code, particularly in hard-to-understand areas.
-   [ x] My changes generates no new warnings.
-   [ ] I'm Hacktoberfest'21 contributor.

### CODE REVIEW

**Comment by girija0707** [comment]
Hey @Koustavjr in order to get checked boxes ticked [x] enter x in between without any spaces

**Review by girija0707 — APPROVED** [review]
Looks good to me

**Comment by girija0707** [comment]
@Koustavjr congratulations PR approved 🔥

**Comment by Koustavjr** [comment]
@girija0707 thank you and will remember not to put space inside the ticked box.

**Pull request merged**
