### PR TITLE
bootstrap_breadcrumb

### PR DESCRIPTION
**Pull request by Koustavjr**
## What is the change?
I have written the documentation for bootstrap breadcrumb.

## Related issue?
closes: #67issue_number

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

-   [x] I have followed the [Code of Conduct](https://github.com/HackClubRAIT/Wizard-Of-Docs/blob/ec224497bce316f7b4736a901f70688f251cca87/CODE_OF_CONDUCT.md).
-   [x] I have  checked there aren't other open [Pull Requests](https://github.com/HackClubRAIT/Frontend-Owls/pulls) for the same update/change.
-   [x] I have you tested the code before submission.
-   [x] I have commented my code, particularly in hard-to-understand areas.
-   [x] My changes generates no new warnings.
-   [ ] I'm Hacktoberfest'21 contributor.

### CODE REVIEW

**Comment by Koustavjr** [comment]
@girija0707 I have created the pr for #67 can u please check it.

**Review by girija0707 — APPROVED** [review]

**Comment by girija0707** [comment]
Good work 👍 @Koustavjr

**Comment by girija0707** [comment]
@Koustavjr hey just take a look this is how you should put the issue no just #number nothing else

**Comment by Koustavjr** [comment]
> 

Oh I got it now🙂

**Comment by Koustavjr** [comment]
> Good work 👍 @Koustavjr but next time try to write more on your own and elaborate a little more on the topic

OK sure....😀

**Pull request merged**
